using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SimpleGateway.Migrations
{
    /// <inheritdoc />
    public partial class AddFinalSignOffSystem : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // FORCE FINAL SIGN-OFF SYSTEM CREATION - Check if tables exist and create if needed
            migrationBuilder.Sql(@"
                -- Create FinalSignOffs table if it doesn't exist
                CREATE TABLE IF NOT EXISTS ""FinalSignOffs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PerformerUsername"" text NOT NULL,
                    ""PerformerDeclarationSigned"" boolean NOT NULL DEFAULT FALSE,
                    ""PerformerSignedBy"" text,
                    ""PerformerSignedAt"" timestamp with time zone,
                    ""SupervisorDeclarationSigned"" boolean NOT NULL DEFAULT FALSE,
                    ""SupervisorSignedBy"" text,
                    ""SupervisorSignedAt"" timestamp with time zone,
                    ""AdvisorDeclarationSigned"" boolean NOT NULL DEFAULT FALSE,
                    ""AdvisorSignedBy"" text,
                    ""AdvisorSignedAt"" timestamp with time zone,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_FinalSignOffs"" PRIMARY KEY (""Id"")
                );
                
                -- Create indexes for FinalSignOffs
                CREATE INDEX IF NOT EXISTS ""IX_FinalSignOffs_PerformerUsername"" 
                    ON ""FinalSignOffs"" (""PerformerUsername"");
            ");

            // Original EF CreateTable call (wrapped in try-catch for safety)
            try
            {
                migrationBuilder.CreateTable(
                    name: "FinalSignOffs",
                    columns: table => new
                    {
                        Id = table.Column<int>(type: "integer", nullable: false)
                            .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                        PerformerUsername = table.Column<string>(type: "text", nullable: false),
                        PerformerDeclarationSigned = table.Column<bool>(type: "boolean", nullable: false),
                        PerformerSignedBy = table.Column<string>(type: "text", nullable: true),
                        PerformerSignedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                        SupervisorDeclarationSigned = table.Column<bool>(type: "boolean", nullable: false),
                        SupervisorSignedBy = table.Column<string>(type: "text", nullable: true),
                        SupervisorSignedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                        AdvisorDeclarationSigned = table.Column<bool>(type: "boolean", nullable: false),
                        AdvisorSignedBy = table.Column<string>(type: "text", nullable: true),
                        AdvisorSignedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                        CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                        UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                    },
                    constraints: table =>
                    {
                        table.PrimaryKey("PK_FinalSignOffs", x => x.Id);
                    });

                migrationBuilder.CreateIndex(
                    name: "IX_FinalSignOffs_PerformerUsername",
                    table: "FinalSignOffs",
                    column: "PerformerUsername");
            }
            catch (Exception ex)
            {
                // Tables already exist via SQL creation above
                Console.WriteLine($"Final Sign-off Migration: Tables already exist or EF creation skipped: {ex.Message}");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FinalSignOffs");
        }
    }
}
